### ISSUE TITLE
Exception on running in Windows 10 cmd

### ISSUE THREAD

**Issue by xenon134** [vyahello/snakegame-cli#5]
```
C:\WINDOWS\system32>python -m snake --run --name pysnake
Running Terminal game called 'pysnake'
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python38\lib\runpy.py", line 192, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files (x86)\Python38\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Program Files (x86)\Python38\lib\site-packages\snake\__main__.py", line 22, in <module>
    easyrun()  # pylint: disable=no-value-for-parameter
  File "C:\Program Files (x86)\Python38\lib\site-packages\click\core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "C:\Program Files (x86)\Python38\lib\site-packages\click\core.py", line 717, in main
    rv = self.invoke(ctx)
  File "C:\Program Files (x86)\Python38\lib\site-packages\click\core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Program Files (x86)\Python38\lib\site-packages\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "C:\Program Files (x86)\Python38\lib\site-packages\snake\__main__.py", line 13, in easyrun
    game.run()
  File "C:\Program Files (x86)\Python38\lib\site-packages\snake\game.py", line 43, in run
    self._window.timeout()
  File "C:\Program Files (x86)\Python38\lib\site-packages\snake\environment\window.py", line 47, in timeout
    self._window().timeout(self._timeout)
  File "C:\Program Files (x86)\Python38\lib\site-packages\snake\environment\window.py", line 41, in _window
    return env.new_window()
  File "C:\Program Files (x86)\Python38\lib\site-packages\snake\environment\terminal.py", line 48, in new_window
    return curses.newwin(self._height, self._width)
_curses.error: curses function returned NULL

```

**Comment by vyahello** [comment]
Hey @festival0156 , sorry but currently Windows platforms are not supported (but only *nix like systems)

I'll add more meaningful exception for Windows users.

**Comment by vyahello** [comment]
Opened a separate ticket for windows support - https://github.com/vyahello/snakegame-cli/issues/6

Closing this ticket

**Comment by vyahello** [comment]
@festival0156 it is now possible to run an application via docker as per https://github.com/vyahello/snakegame-cli/issues/8
